# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{wonki}
  s.version = "0.0.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["rubyyot"]
  s.date = %q{2010-01-12}
  s.description = %q{a Rack and Git based wiki like thing}
  s.email = %q{jamal.hansen@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/wonki.rb",
     "lib/wonki/page_builder.rb",
     "lib/wonki/page_not_found.rb",
     "lib/wonki/wiki_page.rb",
     "test/helper.rb",
     "test/page_builder_test.rb",
     "test/wiki_page_test.rb",
     "wonki.gemspec"
  ]
  s.homepage = %q{http://github.com/rubyyot/wonki}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{a simple Rack and Git based wiki like thing}
  s.test_files = [
    "test/wiki_page_test.rb",
     "test/helper.rb",
     "test/page_builder_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<grit>, [">= 0"])
      s.add_runtime_dependency(%q<flannel>, [">= 0.1.5"])
      s.add_development_dependency(%q<shoulda>, [">= 2.10.2"])
    else
      s.add_dependency(%q<grit>, [">= 0"])
      s.add_dependency(%q<flannel>, [">= 0.1.5"])
      s.add_dependency(%q<shoulda>, [">= 2.10.2"])
    end
  else
    s.add_dependency(%q<grit>, [">= 0"])
    s.add_dependency(%q<flannel>, [">= 0.1.5"])
    s.add_dependency(%q<shoulda>, [">= 2.10.2"])
  end
end

